SUPABASE_URL = "https://rbaawqpeyigwmzukrmvc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYWF3cXBleWlnd216dWtybXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTA0MzM0MjksImV4cCI6MjAwNjAwOTQyOX0.xF-nchgHwH1Xhyi18TfokUVjO2zYipw730IrESBvZ5A"


[global]
# Everything in this section will be available as an environment variable

[userlogin]
globalpassword = "almalasers1234"

[supabase]
DB_PASSWORD = "EverlyQuinn#7665"
SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYWF3cXBleWlnd216dWtybXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTA0MzM0MjksImV4cCI6MjAwNjAwOTQyOX0.xF-nchgHwH1Xhyi18TfokUVjO2zYipw730IrESBvZ5A"
PROJECT_URL = "https://rbaawqpeyigwmzukrmvc.supabase.co"

[openai]
OPENAI_API_KEY = "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"
OPENAI_MODEL_CHATCOMPLETIONS = 'gpt-4-0613'
OPENAI_MODEL_EMBEDDINGS =  'text-embedding-ada-002'
OPENAI_MODEL_COMPLETION = 'text-davinci-003'
OPENAI_ENCODING =  'cl100k_base'
OPENAI_MAX_TOKEN =  8000

[salesforce]
SALESFORCE_USERNAME =  'michael.zozulia@almalasers.com'
SALESFORCE_PASSWORD =  'EverlyQuinn#7665'
SALESFORCE_TOKEN =  '8VY2ZFvXya0eyI1oGCMOZeVc'

[o365]
CLIENT_ID = '1c95ca89-41bf-4aa0-b31c-3af594ae0dc9'
CLIENT_SECRET_VALUE = 'g~c8Q~LoOMuy3o4CtlzytkV3jmAmgmNoRh1OzcHN'
CLIENT_SECRET_KEY = '7258b16d-7699-4cce-9192-0a18473002db'
TENANT_ID = '6d9b0470-8296-4636-a8f7-bd5513eb2bc0'
AUTH_URL = 'https://login.microsoftonline.com/6d9b0470-8296-4636-a8f7-bd5513eb2bc0/oauth2/v2.0/authorize'
ACCESS_TOKEN = "Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6ImxPcFlYRzBrVF9rc29jY04yMzlHakFVZGQzcDVLZTc2cUpXZHhfU3lObHciLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC82ZDliMDQ3MC04Mjk2LTQ2MzYtYThmNy1iZDU1MTNlYjJiYzAvIiwiaWF0IjoxNjkxMjg4MDczLCJuYmYiOjE2OTEyODgwNzMsImV4cCI6MTY5MTI5MTk3MywiYWlvIjoiRTJGZ1lHaitscnpyKy94d1Q4L21QNjgyM1ZWU0FBQT0iLCJhcHBfZGlzcGxheW5hbWUiOiJBbG15QUkiLCJhcHBpZCI6IjFjOTVjYTg5LTQxYmYtNGFhMC1iMzFjLTNhZjU5NGFlMGRjOSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzZkOWIwNDcwLTgyOTYtNDYzNi1hOGY3LWJkNTUxM2ViMmJjMC8iLCJpZHR5cCI6ImFwcCIsIm9pZCI6IjgwNzg3MGNmLTJmNDEtNGNkOC05ZDQxLTdjY2E2ZjI1MDJjNCIsInJoIjoiMC5BUndBY0FTYmJaYUNOa2FvOTcxVkUtc3J3QU1BQUFBQUFBQUF3QUFBQUFBQUFBQWNBQUEuIiwicm9sZXMiOlsiVGVhbVNldHRpbmdzLlJlYWRXcml0ZS5BbGwiLCJBUElDb25uZWN0b3JzLlJlYWRXcml0ZS5BbGwiLCJUZWFtc0FjdGl2aXR5LlJlYWQuQWxsIiwiTWFpbC5SZWFkV3JpdGUiLCJVc2VyLlJlYWRXcml0ZS5BbGwiLCJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuT3duZWRCeSIsIlVzZXJBdXRoZW50aWNhdGlvbk1ldGhvZC5SZWFkV3JpdGUuQWxsIiwiQ2FsZW5kYXJzLlJlYWQiLCJNYWlsLlJlYWRCYXNpYy5BbGwiLCJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuQWxsIiwiVGVhbXNBY3Rpdml0eS5TZW5kIiwiU2l0ZXMuUmVhZFdyaXRlLkFsbCIsIlVzZXIuRW5hYmxlRGlzYWJsZUFjY291bnQuQWxsIiwiU2l0ZXMuTWFuYWdlLkFsbCIsIkZpbGVzLlJlYWRXcml0ZS5BbGwiLCJDYWxlbmRhcnMuUmVhZEJhc2ljLkFsbCIsIk9yZ2FuaXphdGlvbi5SZWFkV3JpdGUuQWxsIiwiQVBJQ29ubmVjdG9ycy5SZWFkLkFsbCIsIk1haWwuUmVhZCIsIlVzZXIuRXhwb3J0LkFsbCIsIkNhbGVuZGFycy5SZWFkV3JpdGUiLCJMaWNlbnNlQXNzaWdubWVudC5SZWFkV3JpdGUuQWxsIiwiTWFpbC5TZW5kIiwiVXNlci5NYW5hZ2VJZGVudGl0aWVzLkFsbCIsIk1haWxib3hTZXR0aW5ncy5SZWFkV3JpdGUiLCJNYWlsLlJlYWRCYXNpYyIsIk1lbWJlci5SZWFkLkhpZGRlbiIsIkFwcGxpY2F0aW9uLlJlYWQuQWxsIiwiU2l0ZXMuRnVsbENvbnRyb2wuQWxsIl0sInN1YiI6IjgwNzg3MGNmLTJmNDEtNGNkOC05ZDQxLTdjY2E2ZjI1MDJjNCIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6IjZkOWIwNDcwLTgyOTYtNDYzNi1hOGY3LWJkNTUxM2ViMmJjMCIsInV0aSI6ImZ5XzZNY3hwSVVtYnN1eTllRUdEQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjA5OTdhMWQwLTBkMWQtNGFjYi1iNDA4LWQ1Y2E3MzEyMWU5MCJdLCJ4bXNfdGNkdCI6MTQ4NDMyMTI3OX0.jKx7FHEiEBJ0DE3_G7c7cN8OAOUx2_LRLiNAwHYrTXlVWz0-7JFcO7FzE-kRNSU6fEVHRiCKCcuygShRGEOcvqATl-nTMjMcvJ6gzzE2Qb9rH3y8ScviteAYhty-tqoa3lOfNLcBLkQGn1CBKGo25a33GgctlWzx_sj_ACTPMKginKmjEdxE5Eikr7Vi6P1XSlA8-fRCZJt6LoaplluXPme-aTupowc6eHnIJkVAcVK9LBL-VDGpurN7hzgN0OAmmM33w_yJRW9d5pwBCzb8_R0-yQLPI_KCu9AxVXLk4CLe3q5AQcM47dmthebsMmwTDC9jZPwyCUdORPqKKW36gA"

[pinecone]
PINECONE_API_KEY =  'f01fb634-92b7-4370-ab48-9cf36200b925'
PINECONE_API_NAME =  'almyai'
PINECONE_API_ENVIRONMENT =  'us-west1-gcp-free'

[serp]
SERP_API_KEY = '5cea8ad504d40e86139eeed0626cba900b102ed17704b48becabf94c2c0b0b99'
SERP_SEARCH_URL = 'https://serpapi.com/search.json'

[extractor]
EXTRACTOR_API_KEY = '77da7c56abc8fa6c702c9d9644810ddc75c00b43'

[robocorp]
ROBOCORP_API_KEY = 'hlH6olXAEWUs0hOo5KJLI8QaOhCEFp4rWA27r40oFgPTcFQ2sMDqOc34zAS7pglmxG0WmHp2ozzLHYjc3hmjsaGGMBryVu7kA9sMxwb1FlulUZmmJ6DFCi9Yo'

[scrapeit]
SCRAPEIT_API_KEY = 'b7d1e018-7799-48c2-9671-47e97d3e20fa'

[serper]
SERPER_API_KEY ='efcf2d0e8a247bfc6c07be144cf087330b39e8b6'

[requesturls]
power_automate_http_salesforce_accounts = 'https://prod-169.westus.logic.azure.com:443/workflows/c3e2ae4987964ac0b801ba15824ed480/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=l2nICTVjfZZzHNfHlYmUFg3lcsHDB7YJcGdxI1Zq6a4'
power_automate_http_salesforce_notes = 'https://prod-50.westus.logic.azure.com:443/workflows/caea1b99acea4162917275ea5a587e9f/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=ZFpgN3z05iNxPP4-19MxvyQ-HGtUnYtEaNInKUyfEeI'
power_automate_http_test = 'https://prod-69.westus.logic.azure.com:443/workflows/ac4ca3abe0ab45178c2a3fd95a8cfa86/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=jLNYRrFZQNZ-BJRGsg19KC4lgzHdcQlLPQin4q_h-oo'
